services:
  fastapi-telegram-bot:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      - TELEGRAM_API_ID=${TELEGRAM_API_ID}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH}
      - TELEGRAM_PHONE_NUMBER=${TELEGRAM_PHONE_NUMBER}
      - TELEGRAM_CHANNEL_IDS=${TELEGRAM_CHANNEL_IDS}
      - DATABASE_URL=postgresql://user:password@db:5432/telegram_bot
    depends_on:
      - db

  db:
    image: postgres:13
    ports:
      - "5434:5432"  # Using 5433 on the host to avoid conflicts
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=telegram_bot
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: